%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\MikeCamp\Downloads\iris.data
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/07/19 15:46:27

%% Initialize variables.
filename = 'C:\Users\MikeCamp\Downloads\iris.data';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
SepalLength = dataArray{:, 1};
SepalWidth = dataArray{:, 2};
PetalLength = dataArray{:, 3};
PetalWidth = dataArray{:, 4};
Class = dataArray{:, 5};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;